package old;

public class Essaituiles {
    /*
    game.Tuile domino1 = new game.Tuile(0, jaune, 0, jaune, 1);
        tuiles.add(domino1);
    game.Tuile domino2 = new game.Tuile(0, jaune, 0, jaune, 2);
        tuiles.add(domino2);
    game.Tuile domino3 = new game.Tuile(0, rouge, 0, rouge, 3);
        tuiles.add(domino3);
    game.Tuile domino4 = new game.Tuile(0, rouge, 0, rouge, 4);
        tuiles.add(domino4);
    game.Tuile domino5 = new game.Tuile(0, rouge, 0, rouge, 5);
        tuiles.add(domino5);
    game.Tuile domino6 = new game.Tuile(0, rouge, 0, rouge, 6);
        tuiles.add(domino6);
    game.Tuile domino7 = new game.Tuile(0, bleu, 0, bleu, 7);
        tuiles.add(domino7);
    game.Tuile domino8 = new game.Tuile(0, bleu, 0, bleu, 8);
        tuiles.add(domino8);
    game.Tuile domino9 = new game.Tuile(0, bleu, 0, bleu, 9);
        tuiles.add(domino9);
    game.Tuile domino10 = new game.Tuile(0, vert, 0, vert, 10);
        tuiles.add(domino10);
    game.Tuile domino11 = new game.Tuile(0, vert, 0, vert, 11);
        tuiles.add(domino11);
    game.Tuile domino12 = new game.Tuile(0, gris, 0, gris, 12);
        tuiles.add(domino12);
    game.Tuile domino13 = new game.Tuile(0, jaune, 0, rouge, 13);
        tuiles.add(domino13);
    game.Tuile domino14 = new game.Tuile(0, jaune, 0, bleu, 14);
        tuiles.add(domino14);
    game.Tuile domino15 = new game.Tuile(0, jaune, 0, vert, 15);
        tuiles.add(domino15);
    game.Tuile domino16 = new game.Tuile(0, jaune, 0, gris, 16);
        tuiles.add(domino16);
    game.Tuile domino17 = new game.Tuile(0, rouge, 0, bleu, 17);
        tuiles.add(domino17);
    game.Tuile domino18 = new game.Tuile(0, rouge, 0, vert, 18);
        tuiles.add(domino18);
    game.Tuile domino19 = new game.Tuile(1, jaune, 0, rouge, 19);
        tuiles.add(domino19);
    game.Tuile domino20 = new game.Tuile(1, jaune, 0, bleu, 20);
        tuiles.add(domino20);
    game.Tuile domino21 = new game.Tuile(1, jaune, 0, vert, 21);
        tuiles.add(domino21);
    game.Tuile domino22 = new game.Tuile(1, jaune, 0, gris, 22);
        tuiles.add(domino22);
    game.Tuile domino23 = new game.Tuile(1, jaune, 0, marron, 23);
        tuiles.add(domino23);
    game.Tuile domino24 = new game.Tuile(1, rouge, 0, jaune, 24);
        tuiles.add(domino24);
    game.Tuile domino25 = new game.Tuile(1, rouge, 0, jaune, 25);
        tuiles.add(domino25);
    game.Tuile domino26 = new game.Tuile(1, rouge, 0, jaune, 26);
        tuiles.add(domino26);
    game.Tuile domino27 = new game.Tuile(1, rouge, 0, jaune, 27);
        tuiles.add(domino27);
    game.Tuile domino28 = new game.Tuile(1, rouge, 0, bleu, 28);
        tuiles.add(domino28);
    game.Tuile domino29 = new game.Tuile(1, rouge, 0, vert, 29);
        tuiles.add(domino29);
    game.Tuile domino30 = new game.Tuile(1, bleu, 0, jaune, 30);
        tuiles.add(domino30);
    game.Tuile domino31 = new game.Tuile(1, bleu, 0, jaune, 31);
        tuiles.add(domino31);
    game.Tuile domino32 = new game.Tuile(1, bleu, 0, rouge, 32);
        tuiles.add(domino32);
    game.Tuile domino33 = new game.Tuile(1, bleu, 0, rouge, 33);
        tuiles.add(domino33);
    game.Tuile domino34 = new game.Tuile(1, bleu, 0, rouge, 34);
        tuiles.add(domino34);
    game.Tuile domino35 = new game.Tuile(1, bleu, 0, rouge, 35);
        tuiles.add(domino35);
    game.Tuile domino36 = new game.Tuile(0, jaune, 1, vert, 36);
        tuiles.add(domino36);
    game.Tuile domino37 = new game.Tuile(0, bleu, 1, vert, 37);
        tuiles.add(domino37);
    game.Tuile domino38 = new game.Tuile(0, jaune, 1, gris, 38);
        tuiles.add(domino38);
    game.Tuile domino39 = new game.Tuile(0, vert, 1, gris, 39);
        tuiles.add(domino39);
    game.Tuile domino40 = new game.Tuile(1, marron, 0, jaune, 40);
        tuiles.add(domino40);
    game.Tuile domino41 = new game.Tuile(0, jaune, 2, vert, 41);
        tuiles.add(domino41);
    game.Tuile domino42 = new game.Tuile(0, bleu, 2, vert, 42);
        tuiles.add(domino42);
    game.Tuile domino43 = new game.Tuile(0, jaune, 2, gris, 43);
        tuiles.add(domino43);
    game.Tuile domino44 = new game.Tuile(0, vert, 2, gris, 44);
        tuiles.add(domino44);
    game.Tuile domino45 = new game.Tuile(2, marron, 0, jaune, 45);
        tuiles.add(domino45);
    game.Tuile domino46 = new game.Tuile(0, gris, 2, marron, 46);
        tuiles.add(domino46);
    game.Tuile domino47 = new game.Tuile(0, gris, 2, marron, 47);
        tuiles.add(domino47);
    game.Tuile domino48 = new game.Tuile(0, jaune, 3, marron, 48);
        tuiles.add(domino48);
        */
}
